base_robot:
  target_height: 0.74 
  deadzone: 0.015

motion_skill_1:
  motion_npz: ../../locomotion_and_motion_tracking/video2robot/data/video_013/npz_holosoma/robot_motion_track_1.npz
  x: 1.99
  y: -0.14
  target_x: 6.579
  target_y: -2.782
  strike_start_frame: 153   
  stand_start_frame:  220    
  motion_training_ratio: 0.90
  kick_foot: right
  kick_ankle_pitch_correction_enabled: true 
  kick_aim_enabled: true
  task_config: task_config_stageB2
